package com.google.android.gms.internal;

import android.content.Context;
import android.content.SharedPreferences.Editor;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;

@zzzn
public final class zzmo {
   private static zzme zzBW = zzme.zza(0, "gads:sdk_core_experiment_id");
   public static final zzme zzBX = zzme.zza(0, "gads:sdk_core_location", (String)"https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
   private static zzme zzBY = zzme.zza(0, "gads:request_builder:singleton_webview", (Boolean)false);
   private static zzme zzBZ = zzme.zza(0, "gads:request_builder:singleton_webview_experiment_id");
   private static zzme zzCa = zzme.zza(0, "gads:sdk_use_dynamic_module", (Boolean)true);
   private static zzme zzCb = zzme.zza(0, "gads:sdk_use_dynamic_module_experiment_id");
   public static final zzme zzCc = zzme.zza(0, "gads:sdk_crash_report_enabled", (Boolean)false);
   public static final zzme zzCd = zzme.zza(0, "gads:sdk_crash_report_full_stacktrace", (Boolean)false);
   public static final zzme zzCe = zzme.zza(0, "gads:sdk_crash_report_class_prefix", (String)"com.google.");
   public static final zzme zzCf = zzme.zza(0, "gads:block_autoclicks", (Boolean)false);
   private static zzme zzCg = zzme.zza(0, "gads:block_autoclicks_experiment_id");
   private static zzme zzCh = zzme.zza(0, "gads:spam_app_context:experiment_id");
   public static final zzme zzCi = zzme.zza(1, "gads:spam_app_context:enabled", (Boolean)false);
   private static zzme zzCj = zzme.zza(1, "gads:http_url_connection_factory:timeout_millis", 10000);
   public static final zzme zzCk = zzme.zza(1, "gads:video_exo_player:version", (String)"1");
   private static zzme zzCl = zzme.zza(0, "gads:video_stream_cache:experiment_id");
   public static final zzme zzCm = zzme.zza(1, "gads:video_stream_cache:limit_count", 5);
   public static final zzme zzCn = zzme.zza(1, "gads:video_stream_cache:limit_space", 8388608);
   public static final zzme zzCo = zzme.zza(1, "gads:video_stream_exo_allocator:segment_size", 65536);
   public static final zzme zzCp = zzme.zza(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
   public static final zzme zzCq = zzme.zza(1, "gads:video_stream_cache:limit_time_sec", 300L);
   public static final zzme zzCr = zzme.zza(1, "gads:video_stream_cache:notify_interval_millis", 125L);
   public static final zzme zzCs = zzme.zza(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
   public static final zzme zzCt = zzme.zza(0, "gads:video:metric_reporting_enabled", (Boolean)false);
   public static final zzme zzCu = zzme.zza(1, "gads:video:metric_frame_hash_times", (String)"");
   public static final zzme zzCv = zzme.zza(1, "gads:video:metric_frame_hash_time_leniency", 500L);
   public static final zzme zzCw = zzme.zza(1, "gads:video:force_watermark", (Boolean)false);
   public static final zzme zzCx = zzme.zza(1, "gads:video:surface_update_min_spacing_ms", 1000L);
   public static final zzme zzCy = zzme.zza(1, "gads:video:spinner:enabled", (Boolean)false);
   public static final zzme zzCz = zzme.zza(1, "gads:video:spinner:scale", 4);
   public static final zzme zzCA = zzme.zza(1, "gads:video:spinner:jank_threshold_ms", 50L);
   public static final zzme zzCB = zzme.zza(1, "gads:video:acquire_decoder_before_play", (Boolean)false);
   public static final zzme zzCC = zzme.zza(1, "gads:memory_bundle:debug_info", (Boolean)false);
   public static final zzme zzCD = zzme.zza(1, "gads:memory_bundle:runtime_info", (Boolean)true);
   public static final zzme zzCE = zzme.zza(1, "gads:video:codec_query_mime_types", (String)"");
   public static final zzme zzCF = zzme.zza(1, "gads:video:codec_query_minimum_version", 16);
   private static zzme zzCG = zzme.zza(0, "gads:ad_id_app_context:enabled", (Boolean)false);
   private static zzme zzCH = zzme.zza(0, "gads:ad_id_app_context:ping_ratio", 0.0F);
   private static zzme zzCI = zzme.zza(0, "gads:ad_id_app_context:experiment_id");
   private static zzme zzCJ = zzme.zzb(0, "gads:looper_for_gms_client:experiment_id");
   public static final zzme zzCK = zzme.zza(0, "gads:looper_for_gms_client:enabled", (Boolean)true);
   public static final zzme zzCL = zzme.zza(0, "gads:sw_ad_request_service:enabled", (Boolean)true);
   private static zzme zzCM = zzme.zza(0, "gads:sw_dynamite:enabled", (Boolean)true);
   public static final zzme zzCN = zzme.zza(1, "gad:mraid:url_banner", (String)"https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
   public static final zzme zzCO = zzme.zza(1, "gad:mraid:url_expanded_banner", (String)"https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
   public static final zzme zzCP = zzme.zza(1, "gad:mraid:url_interstitial", (String)"https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
   public static final zzme zzCQ = zzme.zza(0, "gads:enabled_sdk_csi", (Boolean)false);
   public static final zzme zzCR = zzme.zza(0, "gads:sdk_csi_server", (String)"https://csi.gstatic.com/csi");
   public static final zzme zzCS = zzme.zza(0, "gads:sdk_csi_write_to_file", (Boolean)false);
   public static final zzme zzCT = zzme.zza(0, "gads:enable_content_fetching", (Boolean)true);
   public static final zzme zzCU = zzme.zza(0, "gads:content_length_weight", 1);
   public static final zzme zzCV = zzme.zza(0, "gads:content_age_weight", 1);
   public static final zzme zzCW = zzme.zza(0, "gads:min_content_len", 11);
   public static final zzme zzCX = zzme.zza(0, "gads:fingerprint_number", 10);
   public static final zzme zzCY = zzme.zza(0, "gads:sleep_sec", 10);
   public static final zzme zzCZ = zzme.zza(1, "gads:enable_content_url_hash", (Boolean)true);
   public static final zzme zzDa = zzme.zza(1, "gads:content_vertical_fingerprint_number", 100);
   public static final zzme zzDb = zzme.zza(1, "gads:enable_content_vertical_hash", (Boolean)true);
   public static final zzme zzDc = zzme.zza(1, "gads:content_vertical_fingerprint_bits", 23);
   public static final zzme zzDd = zzme.zza(1, "gads:content_vertical_fingerprint_ngram", 3);
   public static final zzme zzDe = zzme.zza(1, "gads:content_fetch_view_tag_id", (String)"googlebot");
   public static final zzme zzDf = zzme.zza(1, "gads:content_fetch_exclude_view_tag", (String)"none");
   public static final zzme zzDg = zzme.zza(0, "gad:app_index_enabled", (Boolean)true);
   public static final zzme zzDh = zzme.zza(1, "gads:content_fetch_disable_get_title_from_webview", (Boolean)false);
   public static final zzme zzDi = zzme.zza(0, "gads:app_index:without_content_info_present:enabled", (Boolean)true);
   public static final zzme zzDj = zzme.zza(0, "gads:app_index:timeout_ms", 1000L);
   private static zzme zzDk = zzme.zza(0, "gads:app_index:experiment_id");
   private static zzme zzDl = zzme.zza(0, "gads:kitkat_interstitial_workaround:experiment_id");
   public static final zzme zzDm = zzme.zza(0, "gads:kitkat_interstitial_workaround:enabled", (Boolean)true);
   public static final zzme zzDn = zzme.zza(0, "gads:interstitial_follow_url", (Boolean)true);
   public static final zzme zzDo = zzme.zza(0, "gads:interstitial_follow_url:register_click", (Boolean)true);
   private static zzme zzDp = zzme.zza(0, "gads:interstitial_follow_url:experiment_id");
   private static zzme zzDq = zzme.zza(0, "gads:analytics_enabled", (Boolean)true);
   public static final zzme zzDr = zzme.zza(0, "gads:ad_key_enabled", (Boolean)false);
   public static final zzme zzDs = zzme.zza(1, "gads:sai:enabled", (Boolean)false);
   public static final zzme zzDt = zzme.zza(1, "gads:sai:banner_ad_enabled", (Boolean)true);
   public static final zzme zzDu = zzme.zza(1, "gads:sai:native_ad_enabled", (Boolean)true);
   public static final zzme zzDv = zzme.zza(1, "gads:sai:interstitial_ad_enabled", (Boolean)true);
   public static final zzme zzDw = zzme.zza(1, "gads:sai:click_ping_schema", (String)"[\"/aclk\",\"/pcs/click\"]");
   public static final zzme zzDx = zzme.zza(1, "gads:sai:impression_ping_schema", (String)"[\"/adview\"]");
   public static final zzme zzDy = zzme.zza(1, "gads:sai:click_gmsg_enabled", (Boolean)true);
   public static final zzme zzDz = zzme.zza(1, "gads:sai:using_macro:enabled", (Boolean)false);
   public static final zzme zzDA = zzme.zza(1, "gads:sai:ad_event_id_macro_name", (String)"@gw_fbsaeid@");
   public static final zzme zzDB = zzme.zza(1, "gads:sai:timeout_ms", 100L);
   public static final zzme zzDC = zzme.zza(1, "gads:sai:scion_thread_pool_size", 5);
   private static zzme zzDD = zzme.zza(0, "gads:webview_cache_version", 0);
   public static final zzme zzDE = zzme.zza(1, "gads:webview_recycle:enabled", (Boolean)false);
   public static final zzme zzDF = zzme.zza(1, "gads:webview:ignore_over_scroll", (Boolean)true);
   private static zzme zzDG = zzme.zzb(0, "gads:pan:experiment_id");
   public static final zzme zzDH = zzme.zza(1, "gads:rewarded:adapter_initialization_enabled", (Boolean)false);
   public static final zzme zzDI = zzme.zza(1, "gads:rewarded:adapter_timeout_ms", 20000L);
   public static final zzme zzDJ = zzme.zza(1, "gads:app_activity_tracker:enabled", (Boolean)true);
   public static final zzme zzDK = zzme.zza(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500L);
   public static final zzme zzDL;
   public static final zzme zzDM;
   public static final zzme zzDN;
   public static final zzme zzDO;
   public static final zzme zzDP;
   private static zzme zzDQ;
   public static final zzme zzDR;
   public static final zzme zzDS;
   public static final zzme zzDT;
   private static zzme zzDU;
   private static zzme zzDV;
   private static zzme zzDW;
   private static zzme zzDX;
   public static final zzme zzDY;
   public static final zzme zzDZ;
   public static final zzme zzEa;
   public static final zzme zzEb;
   public static final zzme zzEc;
   public static final zzme zzEd;
   public static final zzme zzEe;
   public static final zzme zzEf;
   public static final zzme zzEg;
   public static final zzme zzEh;
   public static final zzme zzEi;
   public static final zzme zzEj;
   public static final zzme zzEk;
   public static final zzme zzEl;
   private static zzme zzEm;
   public static final zzme zzEn;
   public static final zzme zzEo;
   public static final zzme zzEp;
   public static final zzme zzEq;
   public static final zzme zzEr;
   public static final zzme zzEs;
   public static final zzme zzEt;
   public static final zzme zzEu;
   public static final zzme zzEv;
   public static final zzme zzEw;
   private static zzme zzEx;
   private static zzme zzEy;
   private static zzme zzEz;
   private static zzme zzEA;
   public static final zzme zzEB;
   public static final zzme zzEC;
   private static zzme zzED;
   private static zzme zzEE;
   public static final zzme zzEF;
   public static final zzme zzEG;
   public static final zzme zzEH;
   public static final zzme zzEI;
   public static final zzme zzEJ;
   public static final zzme zzEK;
   public static final zzme zzEL;
   public static final zzme zzEM;
   public static final zzme zzEN;
   public static final zzme zzEO;
   public static final zzme zzEP;
   public static final zzme zzEQ;
   public static final zzme zzER;
   public static final zzme zzES;
   public static final zzme zzET;
   public static final zzme zzEU;
   public static final zzme zzEV;
   public static final zzme zzEW;
   public static final zzme zzEX;
   public static final zzme zzEY;
   private static zzme zzEZ;
   public static final zzme zzFa;
   public static final zzme zzFb;
   public static final zzme zzFc;
   public static final zzme zzFd;
   public static final zzme zzFe;
   private static zzme zzFf;
   private static zzme zzFg;
   public static final zzme zzFh;
   public static final zzme zzFi;
   private static zzme zzFj;
   private static zzme zzFk;
   public static final zzme zzFl;
   public static final zzme zzFm;
   public static final zzme zzFn;
   public static final zzme zzFo;
   private static zzme zzFp;
   public static final zzme zzFq;
   private static zzme zzFr;
   public static final zzme zzFs;
   public static final zzme zzFt;
   public static final zzme zzFu;
   private static zzme zzFv;
   public static final zzme zzFw;
   public static final zzme zzFx;
   public static final zzme zzFy;
   public static final zzme zzFz;
   public static final zzme zzFA;
   public static final zzme zzFB;
   public static final zzme zzFC;
   public static final zzme zzFD;
   public static final zzme zzFE;
   public static final zzme zzFF;
   public static final zzme zzFG;
   public static final zzme zzFH;
   private static zzme zzFI;
   private static zzme zzFJ;
   public static final zzme zzFK;
   private static zzme zzFL;
   private static zzme zzFM;
   private static zzme zzFN;
   public static final zzme zzFO;
   private static zzme zzFP;
   public static final zzme zzFQ;
   private static zzme zzFR;
   public static final zzme zzFS;
   public static final zzme zzFT;
   public static final zzme zzFU;
   public static final zzme zzFV;
   public static final zzme zzFW;
   public static final zzme zzFX;
   private static zzme zzFY;
   private static zzme zzFZ;
   private static zzme zzGa;
   public static final zzme zzGb;
   public static final zzme zzGc;
   public static final zzme zzGd;
   public static final zzme zzGe;
   public static final zzme zzGf;
   private static zzme zzGg;
   private static zzme zzGh;
   private static zzme zzGi;
   public static final zzme zzGj;
   public static final zzme zzGk;
   public static final zzme zzGl;
   public static final zzme zzGm;
   private static zzme zzGn;
   public static final zzme zzGo;
   public static final zzme zzGp;
   public static final zzme zzGq;
   public static final zzme zzGr;
   public static final zzme zzGs;
   public static final zzme zzGt;
   public static final zzme zzGu;
   public static final zzme zzGv;
   public static final zzme zzGw;
   public static final zzme zzGx;
   public static final zzme zzGy;
   public static final zzme zzGz;
   public static final zzme zzGA;
   public static final zzme zzGB;
   public static final zzme zzGC;
   private static zzme zzGD;
   public static final zzme zzGE;
   public static final zzme zzGF;
   public static final zzme zzGG;
   private static byte[] zzGH;

   public static void initialize(Context var0) {
      zzait.zzb(new zzmp(var0));
      zzme var2 = zzEm;
      int var1;
      if ((var1 = ((Integer)com.google.android.gms.ads.internal.zzbs.zzbL().zzd(var2)).intValue()) > 0 && zzGH == null) {
         zzGH = new byte[var1];
      }

   }

   public static void zza(Context var0, int var1, JSONObject var2) {
      com.google.android.gms.ads.internal.zzbs.zzbJ();
      Editor var3 = var0.getSharedPreferences("google_ads_flags", 0).edit();
      com.google.android.gms.ads.internal.zzbs.zzbK().zza(var3, 1, var2);
      com.google.android.gms.ads.internal.zzbs.zzbJ();
      var3.commit();
   }

   public static List zzdJ() {
      return com.google.android.gms.ads.internal.zzbs.zzbK().zzdJ();
   }

   public static List zzdK() {
      return com.google.android.gms.ads.internal.zzbs.zzbK().zzdK();
   }

   static {
      zzDL = zzme.zza(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5L));
      zzDM = zzme.zza(1, "gads:adid_values_in_adrequest:enabled", (Boolean)false);
      zzDN = zzme.zza(1, "gads:adid_values_in_adrequest:timeout", 2000L);
      zzDO = zzme.zza(1, "gads:disable_adid_values_in_ms", (Boolean)false);
      zzDP = zzme.zza(1, "gads:enable_ad_loader_manager", (Boolean)true);
      zzDQ = zzme.zza(0, "gads:ad_serving:enabled", (Boolean)true);
      zzDR = zzme.zza(1, "gads:ad_manager_enforce_arp_invariant:enabled", (Boolean)false);
      zzDS = zzme.zza(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000L);
      zzDT = zzme.zza(1, "gads:interstitial_ad_immersive_mode", (Boolean)true);
      zzDU = zzme.zza(1, "gads:impression_optimization_enabled", (Boolean)false);
      zzDV = zzme.zza(1, "gads:banner_ad_pool:schema", (String)"customTargeting");
      zzDW = zzme.zza(1, "gads:banner_ad_pool:max_queues", 3);
      zzDX = zzme.zza(1, "gads:banner_ad_pool:max_pools", 3);
      zzDY = zzme.zza(1, "gads:interstitial_ad_pool:enabled", (Boolean)false);
      zzDZ = zzme.zza(1, "gads:interstitial_ad_pool:enabled_for_rewarded", (Boolean)false);
      zzEa = zzme.zza(1, "gads:interstitial_ad_pool:schema", (String)"customTargeting");
      zzEb = zzme.zza(1, "gads:interstitial_ad_pool:request_exclusions", (String)"com.google.ads.mediation.admob.AdMobAdapter/_ad");
      zzEc = zzme.zza(1, "gads:interstitial_ad_pool:max_pools", 3);
      zzEd = zzme.zza(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
      zzEe = zzme.zza(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
      zzEf = zzme.zza(1, "gads:interstitial_ad_pool:ad_unit_exclusions", (String)"(?!)");
      zzEg = zzme.zza(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
      zzEh = zzme.zza(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
      zzEi = zzme.zza(1, "gads:interstitial_ad_pool:discard_thresholds", 0L);
      zzEj = zzme.zza(1, "gads:interstitial_ad_pool:miss_thresholds", 0L);
      zzEk = zzme.zza(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0F);
      zzEl = zzme.zza(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0F);
      zzEm = zzme.zza(1, "gads:heap_wastage:bytes", 0);
      zzEn = zzme.zza(1, "gads:spherical_video:vertex_shader", (String)"");
      zzEo = zzme.zza(1, "gads:spherical_video:fragment_shader", (String)"");
      zzEp = zzme.zza(0, "gads:log:verbose_enabled", (Boolean)false);
      zzEq = zzme.zza(1, "gads:include_local_global_rectangles", (Boolean)false);
      zzEr = zzme.zza(1, "gads:position_watcher:throttle_ms", 200L);
      zzEs = zzme.zza(1, "gads:include_lock_screen_apps_for_visibility", (Boolean)true);
      zzEt = zzme.zza(0, "gads:device_info_caching:enabled", (Boolean)true);
      zzEu = zzme.zza(0, "gads:device_info_caching_expiry_ms:expiry", 300000L);
      zzEv = zzme.zza(0, "gads:gen204_signals:enabled", (Boolean)false);
      zzEw = zzme.zza(0, "gads:webview:error_reporting_enabled", (Boolean)false);
      zzEx = zzme.zza(0, "gads:adid_reporting:enabled", (Boolean)false);
      zzEy = zzme.zza(0, "gads:ad_settings_page_reporting:enabled", (Boolean)false);
      zzEz = zzme.zza(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", (Boolean)false);
      zzEA = zzme.zza(0, "gads:request_pkg:enabled", (Boolean)true);
      zzEB = zzme.zza(1, "gads:gmsg:disable_back_button:enabled", (Boolean)true);
      zzEC = zzme.zza(0, "gads:gmsg:video_meta:enabled", (Boolean)true);
      zzED = zzme.zza(0, "gads:gmsg:video_meta:experiment_id");
      zzEE = zzme.zza(1, "gads:network:cache_prediction_duration_s", 300L);
      zzEF = zzme.zza(1, "gads:network:network_prediction_timeout_ms", 2000L);
      zzEG = zzme.zza(0, "gads:mediation:dynamite_first:admobadapter", (Boolean)true);
      zzEH = zzme.zza(0, "gads:mediation:dynamite_first:adurladapter", (Boolean)true);
      zzEI = zzme.zza(1, "gads:bypass_adrequest_service_for_inlined_mediation", (Boolean)true);
      zzEJ = zzme.zza(0, "gads:resolve_future:default_timeout_ms", 30000L);
      zzEK = zzme.zza(0, "gads:ad_loader:timeout_ms", 60000L);
      zzEL = zzme.zza(0, "gads:rendering:timeout_ms", 60000L);
      zzEM = zzme.zza(0, "gads:adshield:enable_adshield_instrumentation", (Boolean)false);
      zzEN = zzme.zza(1, "gads:gestures:task_timeout", 2000L);
      zzEO = zzme.zza(1, "gads:gestures:encrypt_size_limit:enabled", (Boolean)false);
      zzEP = zzme.zza(1, "gads:gestures:adb_query:enabled", (Boolean)false);
      zzEQ = zzme.zza(1, "gads:gestures:adb_click:enabled", (Boolean)false);
      zzER = zzme.zza(1, "gads:gestures:orn_caching:enabled", (Boolean)true);
      zzES = zzme.zza(1, "gads:gestures:oc:enabled", (Boolean)false);
      zzET = zzme.zza(1, "gads:gestures:ts", 1);
      zzEU = zzme.zza(1, "gads:gestures:td:enabled", (Boolean)false);
      zzEV = zzme.zza(1, "gads:gestures:tdvs:enabled", (Boolean)false);
      zzEW = zzme.zza(1, "gads:gestures:tuvs:enabled", (Boolean)false);
      zzEX = zzme.zza(1, "gads:gestures:tvvs:enabled", (Boolean)false);
      zzEY = zzme.zza(1, "gads:gestures:vd:enabled", (Boolean)false);
      zzEZ = zzme.zza(1, "gads:gestures:pk", (String)"");
      zzFa = zzme.zza(1, "gads:gestures:check_initialization_thread:enabled", (Boolean)false);
      zzFb = zzme.zza(1, "gads:gestures:get_query_in_non_ui_thread:enabled", (Boolean)true);
      zzFc = zzme.zza(0, "gass:enabled", (Boolean)true);
      zzFd = zzme.zza(0, "gass:enable_int_signal", (Boolean)true);
      zzFe = zzme.zza(0, "gass:enable_ad_attestation_signal", (Boolean)true);
      zzFf = zzme.zza(0, "gads:adid_notification:first_party_check:enabled", (Boolean)true);
      zzFg = zzme.zza(0, "gads:edu_device_helper:enabled", (Boolean)true);
      zzFh = zzme.zza(0, "gads:support_screen_shot", (Boolean)true);
      zzFi = zzme.zza(0, "gads:use_get_drawing_cache_for_screenshot:enabled", (Boolean)true);
      zzFj = zzme.zza(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
      zzFk = zzme.zza(1, "gads:sdk_core_constants:experiment_id");
      zzFl = zzme.zza(1, "gads:sdk_core_constants:caps", (String)"");
      zzFm = zzme.zza(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12L));
      zzFn = zzme.zza(0, "gads:js_flags:mf", (Boolean)false);
      zzFo = zzme.zza(0, "gads:custom_render:ping_on_ad_rendered", (Boolean)false);
      zzFp = zzme.zza(0, "gads:native:engine_url", (String)"//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
      zzFq = zzme.zza(1, "gads:native:engine_url_with_protocol", (String)"https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
      zzFr = zzme.zza(1, "gads:native:video_url", (String)"//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_video_ads.html");
      zzFs = zzme.zza(1, "gads:native:video_url_with_protocol", (String)"https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_video_ads.html");
      zzFt = zzme.zza(1, "gads:singleton_webview_native", (Boolean)false);
      zzFu = zzme.zza(1, "gads:native_initialize_webview_request_time", (Boolean)false);
      zzFv = zzme.zza(1, "gads:singleton_webview_native:experiment_id");
      zzFw = zzme.zza(1, "gads:enable_untrack_view_native", (Boolean)true);
      zzFx = zzme.zza(1, "gads:ignore_untrack_view_google_native", (Boolean)true);
      zzFy = zzme.zza(1, "gads:reset_listeners_preparead_native", (Boolean)true);
      zzFz = zzme.zza(1, "gads:native_video_load_timeout", 10);
      zzFA = zzme.zza(1, "gads:ad_choices_content_description", (String)"Ad Choices Icon");
      zzFB = zzme.zza(1, "gads:clamp_native_video_player_dimensions", (Boolean)true);
      zzFC = zzme.zza(1, "gads:enable_store_active_view_state", (Boolean)false);
      zzFD = zzme.zza(1, "gads:fluid_ad:use_wrap_content_height", (Boolean)false);
      zzFE = zzme.zza(0, "gads:method_tracing:enabled", (Boolean)false);
      zzFF = zzme.zza(0, "gads:method_tracing:duration_ms", 30000L);
      zzFG = zzme.zza(0, "gads:method_tracing:count", 5);
      zzFH = zzme.zza(0, "gads:method_tracing:filesize", 134217728);
      zzFI = zzme.zza(1, "gads:auto_location_for_coarse_permission", (Boolean)false);
      zzFJ = zzme.zzb(1, "gads:auto_location_for_coarse_permission:experiment_id");
      zzFK = zzme.zza(1, "gads:auto_location_timeout", 2000L);
      zzFL = zzme.zzb(1, "gads:auto_location_timeout:experiment_id");
      zzFM = zzme.zza(1, "gads:auto_location_interval", -1L);
      zzFN = zzme.zzb(1, "gads:auto_location_interval:experiment_id");
      zzFO = zzme.zza(1, "gads:fetch_app_settings_using_cld:enabled", (Boolean)false);
      zzFP = zzme.zza(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
      zzFQ = zzme.zza(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000L);
      zzFR = zzme.zza(0, "gads:afs:csa:experiment_id");
      zzFS = zzme.zza(0, "gads:afs:csa_webview_gmsg_ad_failed", (String)"gmsg://noAdLoaded");
      zzFT = zzme.zza(0, "gads:afs:csa_webview_gmsg_script_load_failed", (String)"gmsg://scriptLoadFailed");
      zzFU = zzme.zza(0, "gads:afs:csa_webview_gmsg_ad_loaded", (String)"gmsg://adResized");
      zzFV = zzme.zza(0, "gads:afs:csa_webview_static_file_path", (String)"/afs/ads/i/webview.html");
      zzFW = zzme.zza(0, "gads:afs:csa_webview_custom_domain_param_key", (String)"csa_customDomain");
      zzFX = zzme.zza(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000L);
      zzFY = zzme.zza(0, "gads:afs:csa_ad_manager_enabled", (Boolean)true);
      zzFZ = zzme.zza(1, "gads:parental_controls:send_from_client", (Boolean)true);
      zzGa = zzme.zza(1, "gads:parental_controls:cache_results", (Boolean)true);
      zzGb = zzme.zza(1, "gads:parental_controls:timeout", 2000L);
      zzGc = zzme.zza(0, "gads:safe_browsing:api_key", (String)"AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
      zzGd = zzme.zza(0, "gads:safe_browsing:safety_net:delay_ms", 2000L);
      zzGe = zzme.zza(0, "gads:safe_browsing:debug", (Boolean)false);
      zzGf = zzme.zza(0, "gads:webview_cookie:enabled", (Boolean)true);
      zzGg = zzme.zza(1, "gads:cache:ad_request_timeout_millis", 250);
      zzGh = zzme.zza(1, "gads:cache:max_concurrent_downloads", 10);
      zzGi = zzme.zza(1, "gads:cache:javascript_timeout_millis", 5000L);
      zzGj = zzme.zza(1, "gads:cache:bind_on_foreground", (Boolean)false);
      zzGk = zzme.zza(1, "gads:cache:bind_on_init", (Boolean)false);
      zzGl = zzme.zza(1, "gads:cache:bind_on_request", (Boolean)false);
      zzGm = zzme.zza(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30L));
      zzGn = zzme.zza(1, "gads:cache:use_cache_data_source", (Boolean)false);
      zzGo = zzme.zza(1, "gads:chrome_custom_tabs:enabled", (Boolean)true);
      zzGp = zzme.zza(1, "gads:chrome_custom_tabs_browser:enabled", (Boolean)false);
      zzGq = zzme.zza(1, "gads:chrome_custom_tabs:disabled", (Boolean)false);
      zzGr = zzme.zza(1, "gads:drx_in_app_preview:enabled", (Boolean)true);
      zzGs = zzme.zza(1, "gads:drx_debug_signals:enabled", (Boolean)true);
      zzGt = zzme.zza(1, "gads:drx_debug:debug_device_linking_url", (String)"https://www.google.com/dfp/linkDevice");
      zzGu = zzme.zza(1, "gads:drx_debug:in_app_preview_status_url", (String)"https://www.google.com/dfp/inAppPreview");
      zzGv = zzme.zza(1, "gads:drx_debug:debug_signal_status_url", (String)"https://www.google.com/dfp/debugSignals");
      zzGw = zzme.zza(1, "gads:drx_debug:send_debug_data_url", (String)"https://www.google.com/dfp/sendDebugData");
      zzGx = zzme.zza(1, "gads:drx_debug:timeout_ms", 5000);
      zzGy = zzme.zza(1, "gad:pixel_dp_comparision_multiplier", 1);
      zzGz = zzme.zza(1, "gad:interstitial_for_multi_window", (Boolean)false);
      zzGA = zzme.zza(1, "gad:interstitial_ad_stay_active_in_multi_window", (Boolean)false);
      zzGB = zzme.zza(1, "gad:interstitial:close_button_padding_dip", 0);
      zzGC = zzme.zza(1, "gads:clearcut_logging:enabled", (Boolean)false);
      zzGD = zzme.zza(1, "gads:clearcut_abtest:enabled", (Boolean)false);
      zzGE = zzme.zza(1, "gads:clearcut_messageTime:ms", 60000);
      zzGF = zzme.zza(0, "gad:force_local_ad_request_service:enabled", (Boolean)false);
      zzGG = zzme.zza(1, "gad:http_redirect_max_count:times", 8);
   }
}
