package com.google.android.gms.internal;

import com.google.android.gms.drive.metadata.MetadataField;
import com.google.android.gms.drive.metadata.zzb;
import com.google.android.gms.drive.metadata.internal.zzi;
import com.google.android.gms.drive.metadata.internal.zzo;
import com.google.android.gms.drive.metadata.internal.zzs;
import com.google.android.gms.drive.metadata.internal.zzt;
import com.google.android.gms.drive.metadata.internal.zzu;
import java.util.Collections;

public final class zzbrc {
   public static final MetadataField zzaPQ;
   public static final MetadataField zzaPR;
   public static final zzbrf zzaPS;
   public static final MetadataField zzaPT;
   public static final MetadataField zzaPU;
   public static final MetadataField zzaPV;
   public static final MetadataField zzaPW;
   public static final MetadataField zzaPX;
   public static final MetadataField zzaPY;
   public static final MetadataField zzaPZ;
   public static final MetadataField zzaQa;
   public static final MetadataField zzaQb;
   public static final MetadataField zzaQc;
   public static final MetadataField zzaQd;
   public static final MetadataField zzaQe;
   public static final zzbrg zzaQf;
   public static final MetadataField zzaQg;
   public static final MetadataField zzaQh;
   public static final MetadataField zzaQi;
   public static final MetadataField zzaQj;
   public static final MetadataField zzaQk;
   public static final MetadataField zzaQl;
   public static final MetadataField zzaQm;
   public static final zzbrh zzaQn;
   public static final MetadataField zzaQo;
   public static final zzb zzaQp;
   public static final zzu zzaQq;
   public static final zzu zzaQr;
   public static final zzo zzaQs;
   public static final zzbri zzaQt;
   public static final zzbrk zzaQu;
   public static final MetadataField zzaQv;
   public static final zzbrl zzaQw;
   public static final zzbrm zzaQx;
   public static final MetadataField zzaQy;
   public static final MetadataField zzaQz;
   public static final MetadataField zzaQA;
   public static final com.google.android.gms.drive.metadata.internal.zzb zzaQB;
   public static final MetadataField zzaQC;
   public static final MetadataField zzaQD;
   public static final zzbrj zzaQE;
   public static final MetadataField zzaQF;
   public static final MetadataField zzaQG;

   static {
      zzaPQ = zzbrw.zzaQO;
      zzaPR = new zzt("alternateLink", 4300000);
      zzaPS = new zzbrf(5000000);
      zzaPT = new zzt("description", 4300000);
      zzaPU = new zzt("embedLink", 4300000);
      zzaPV = new zzt("fileExtension", 4300000);
      zzaPW = new zzi("fileSize", 4300000);
      zzaPX = new zzt("folderColorRgb", 7500000);
      zzaPY = new com.google.android.gms.drive.metadata.internal.zzb("hasThumbnail", 4300000);
      zzaPZ = new zzt("indexableText", 4300000);
      zzaQa = new com.google.android.gms.drive.metadata.internal.zzb("isAppData", 4300000);
      zzaQb = new com.google.android.gms.drive.metadata.internal.zzb("isCopyable", 4300000);
      zzaQc = new com.google.android.gms.drive.metadata.internal.zzb("isEditable", 4100000);
      zzaQd = new zzbrd("isExplicitlyTrashed", Collections.singleton("trashed"), Collections.emptySet(), 7000000);
      zzaQe = new com.google.android.gms.drive.metadata.internal.zzb("isLocalContentUpToDate", 7800000);
      zzaQf = new zzbrg("isPinned", 4100000);
      zzaQg = new com.google.android.gms.drive.metadata.internal.zzb("isOpenable", 7200000);
      zzaQh = new com.google.android.gms.drive.metadata.internal.zzb("isRestricted", 4300000);
      zzaQi = new com.google.android.gms.drive.metadata.internal.zzb("isShared", 4300000);
      zzaQj = new com.google.android.gms.drive.metadata.internal.zzb("isGooglePhotosFolder", 7000000);
      zzaQk = new com.google.android.gms.drive.metadata.internal.zzb("isGooglePhotosRootFolder", 7000000);
      zzaQl = new com.google.android.gms.drive.metadata.internal.zzb("isTrashable", 4400000);
      zzaQm = new com.google.android.gms.drive.metadata.internal.zzb("isViewed", 4300000);
      zzaQn = new zzbrh(4100000);
      zzaQo = new zzt("originalFilename", 4300000);
      zzaQp = new zzs("ownerNames", 4300000);
      zzaQq = new zzu("lastModifyingUser", 6000000);
      zzaQr = new zzu("sharingUser", 6000000);
      zzaQs = new zzo(4100000);
      zzaQt = new zzbri("quotaBytesUsed", 4300000);
      zzaQu = new zzbrk("starred", 4100000);
      zzaQv = new zzbre("thumbnail", Collections.emptySet(), Collections.emptySet(), 4400000);
      zzaQw = new zzbrl("title", 4100000);
      zzaQx = new zzbrm("trashed", 4100000);
      zzaQy = new zzt("webContentLink", 4300000);
      zzaQz = new zzt("webViewLink", 4300000);
      zzaQA = new zzt("uniqueIdentifier", 5000000);
      zzaQB = new com.google.android.gms.drive.metadata.internal.zzb("writersCanShare", 6000000);
      zzaQC = new zzt("role", 6000000);
      zzaQD = new zzt("md5Checksum", 7000000);
      zzaQE = new zzbrj(7000000);
      zzaQF = new zzt("recencyReason", 8000000);
      zzaQG = new com.google.android.gms.drive.metadata.internal.zzb("subscribed", 8000000);
   }
}
