package com.google.android.gms.internal;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.Status;
import com.google.android.gms.common.api.TransformedResult;
import com.google.android.gms.common.internal.zzbo;
import java.util.concurrent.TimeUnit;

public final class zzbeh extends PendingResult {
   private final Status mStatus;

   public zzbeh(Status var1) {
      zzbo.zzb(var1, "Status must not be null");
      zzbo.zzb(!var1.isSuccess(), "Status must not be success");
      this.mStatus = var1;
   }

   @NonNull
   final Status getStatus() {
      return this.mStatus;
   }

   @NonNull
   public final Result await() {
      throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
   }

   @NonNull
   public final Result await(long var1, @NonNull TimeUnit var3) {
      throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
   }

   public final void cancel() {
      throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
   }

   public final boolean isCanceled() {
      throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
   }

   public final void setResultCallback(@NonNull ResultCallback var1) {
      throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
   }

   public final void setResultCallback(@NonNull ResultCallback var1, long var2, @NonNull TimeUnit var4) {
      throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
   }

   public final void zza(@NonNull PendingResult.zza var1) {
      throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
   }

   @NonNull
   public final TransformedResult then(@NonNull ResultTransform var1) {
      throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
   }

   @Nullable
   public final Integer zzpo() {
      throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
   }
}
