package com.google.android.gms.internal;

public final class zzans {
   private static zzant zzahe = zzant.zza("analytics.service_enabled", false, false);
   public static zzant zzahf = zzant.zza("analytics.service_client_enabled", true, true);
   public static zzant zzahg = zzant.zzc("analytics.log_tag", "GAv4", "GAv4-SVC");
   private static zzant zzahh = zzant.zza("analytics.max_tokens", 60L, 60L);
   private static zzant zzahi = zzant.zza("analytics.tokens_per_sec", 0.5F, 0.5F);
   public static zzant zzahj = zzant.zza("analytics.max_stored_hits", 2000, 20000);
   private static zzant zzahk = zzant.zza("analytics.max_stored_hits_per_app", 2000, 2000);
   public static zzant zzahl = zzant.zza("analytics.max_stored_properties_per_app", 100, 100);
   public static zzant zzahm = zzant.zza("analytics.local_dispatch_millis", 1800000L, 120000L);
   public static zzant zzahn = zzant.zza("analytics.initial_local_dispatch_millis", 5000L, 5000L);
   private static zzant zzaho = zzant.zza("analytics.min_local_dispatch_millis", 120000L, 120000L);
   private static zzant zzahp = zzant.zza("analytics.max_local_dispatch_millis", 7200000L, 7200000L);
   public static zzant zzahq = zzant.zza("analytics.dispatch_alarm_millis", 7200000L, 7200000L);
   public static zzant zzahr = zzant.zza("analytics.max_dispatch_alarm_millis", 32400000L, 32400000L);
   public static zzant zzahs = zzant.zza("analytics.max_hits_per_dispatch", 20, 20);
   public static zzant zzaht = zzant.zza("analytics.max_hits_per_batch", 20, 20);
   public static zzant zzahu;
   public static zzant zzahv;
   public static zzant zzahw;
   public static zzant zzahx;
   public static zzant zzahy;
   public static zzant zzahz;
   public static zzant zzahA;
   private static zzant zzahB;
   public static zzant zzahC;
   public static zzant zzahD;
   public static zzant zzahE;
   public static zzant zzahF;
   public static zzant zzahG;
   private static zzant zzahH;
   public static zzant zzahI;
   public static zzant zzahJ;
   public static zzant zzahK;
   private static zzant zzahL;
   private static zzant zzahM;
   public static zzant zzahN;
   public static zzant zzahO;
   public static zzant zzahP;
   private static zzant zzahQ;
   private static zzant zzahR;
   public static zzant zzahS;
   public static zzant zzahT;
   public static zzant zzahU;

   static {
      String var0 = "http://www.google-analytics.com";
      zzahu = zzant.zzc("analytics.insecure_host", "http://www.google-analytics.com", var0);
      var0 = "https://ssl.google-analytics.com";
      zzahv = zzant.zzc("analytics.secure_host", "https://ssl.google-analytics.com", var0);
      var0 = "/collect";
      zzahw = zzant.zzc("analytics.simple_endpoint", "/collect", var0);
      var0 = "/batch";
      zzahx = zzant.zzc("analytics.batching_endpoint", "/batch", var0);
      zzahy = zzant.zza("analytics.max_get_length", 2036, 2036);
      zzahz = zzant.zzc("analytics.batching_strategy.k", zzana.zzagK.name(), zzana.zzagK.name());
      zzahA = zzant.zzc("analytics.compression_strategy.k", var0 = zzang.zzagR.name(), var0);
      zzahB = zzant.zza("analytics.max_hits_per_request.k", 20, 20);
      zzahC = zzant.zza("analytics.max_hit_length.k", 8192, 8192);
      zzahD = zzant.zza("analytics.max_post_length.k", 8192, 8192);
      zzahE = zzant.zza("analytics.max_batch_post_length", 8192, 8192);
      var0 = "404,502";
      zzahF = zzant.zzc("analytics.fallback_responses.k", "404,502", var0);
      zzahG = zzant.zza("analytics.batch_retry_interval.seconds.k", 3600, 3600);
      zzahH = zzant.zza("analytics.service_monitor_interval", 86400000L, 86400000L);
      zzahI = zzant.zza("analytics.http_connection.connect_timeout_millis", 60000, 60000);
      zzahJ = zzant.zza("analytics.http_connection.read_timeout_millis", 61000, 61000);
      zzahK = zzant.zza("analytics.campaigns.time_limit", 86400000L, 86400000L);
      var0 = "";
      zzahL = zzant.zzc("analytics.first_party_experiment_id", "", var0);
      zzahM = zzant.zza("analytics.first_party_experiment_variant", 0, 0);
      zzahN = zzant.zza("analytics.test.disable_receiver", false, false);
      zzahO = zzant.zza("analytics.service_client.idle_disconnect_millis", 10000L, 10000L);
      zzahP = zzant.zza("analytics.service_client.connect_timeout_millis", 5000L, 5000L);
      zzahQ = zzant.zza("analytics.service_client.second_connect_delay_millis", 5000L, 5000L);
      zzahR = zzant.zza("analytics.service_client.unexpected_reconnect_millis", 60000L, 60000L);
      zzahS = zzant.zza("analytics.service_client.reconnect_throttle_millis", 1800000L, 1800000L);
      zzahT = zzant.zza("analytics.monitoring.sample_period_millis", 86400000L, 86400000L);
      zzahU = zzant.zza("analytics.initialization_warning_threshold", 5000L, 5000L);
   }
}
